image: vuejs/ci

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  paths:
    - node_modules
  key: project

stages:
  - install
  - test
  - build
  - pages

install:
  stage: install
  script: npm install

test:
  stage: install
  script: npm run lint

build:
  stage: build
  script: npm run build

pages:
  stage: pages
  script: mv public dummy && mv dist public
  artifacts:
    paths:
      - public
