include:
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: templates/release.yml
  - project: nosana-ci/tools/cicd/gitlab-ci
    file: templates/cacheflush.yml

.npm:
  image: node:16
  cache:
    paths:
      - node_modules
    key: $CI_COMMIT_SHORT_SHA

build:
  extends: .npm
  stage: build
  script: npm ci
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test:
  extends: .npm
  stage: test
  script: npm run lint
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  extends: .npm
  stage: deploy
  script:
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release:
  extends: .release
  stage: .post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cacheflush:
  extends: .cacheflush
  stage: .post
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
