image: node:14

stages:
  - test
  - deploy
  - post

test:
  stage: test
  script:
    - npm ci
    - npm run lint
  only:
    - merge_requests
    - main

pages:
  stage: deploy
  script:
    - npm ci
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  stage: post
  script: release.sh
  only:
    - main

cacheflush:
  stage: post
  script:
    - |
      curl \
        --header "Authorization: Bearer $CF_TOKEN_CACHE_PURGE_NOSANA_IO" -H "Content-Type: application/json" \
        --data '{"purge_everything":true}' \
        "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID_NOSANA_IO/purge_cache"
  only:
    - main
