image: vuejs/ci

pages:
  script:
    - npm install
    - npm run build
    - mv public dummy # rename the existing public
    - mv dist public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
