image: vuejs/ci

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  paths:
    - node_modules
  key: project

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: npm install

test:
  stage: test
  script: npm run lint

pages:
  stage: deploy
  script:
    - npm run build
    - mv public dummy # rename existing public directory..
    - mv dist public
  artifacts:
    paths:
      - public
